version: '3.7'
services:

  mysql:
    image: mysql:latest
    container_name: mysql-qa58
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass

  postgres:
    image: postgres:13-alpine
    container_name: postgres-qa58
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_USER=app
      - POSTGRES_DB=app

  node-app:
    build: ./artifacts/gate-simulator
    image: node-app:1.0
    container_name: node-qa58
    ports:
      - '9999:9999'
